name = "multi-signature-wallet-connector"

gas_price = '0.025uarch'
gas_adjustment = 1.3
account_prefix = 'archway'

[networks.testnet]
chain_id = 'constantine-3'
network_variant = 'Shared'
grpc_endpoint = 'https://grpc.constantine.archway.tech:443'
rpc_endpoint = 'https://rpc.constantine.archway.tech:443'

[wasm]
optimizer_version = '0.12.13'
